### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by PolinaDominion** [a13xh7/QaraTMS#10]
Hello.
There is this bug:
1. I add a new case A-555 (for example) to the repository
2. I change the position of this case, for example, I make it the first A-555 - No. 1
3. I create a test run for all cases in the repository

I am waiting:
Case A-555 will be number 1

In fact:
Case A-555 - the last case in the section

http://sabir.greenred.ru/chrome_EtheW1MMu5.png
Thanks for your hard work and support!

**Comment by a13xh7** [comment]
@PolinaDominion fixed for test runs and test plans
