### ISSUE TITLE
Cannot add Test Suite or Test Case

### ISSUE THREAD

**Issue by libregeek** [a13xh7/QaraTMS#20]
I installed QaraTMS on Linux+Apache+MySQL and was able to login without any issues. I was also able to create a project and a default repository. However, when I tried to create the Test Suite the following error occurred. Could you please help me to fix this issue?

<img width="959" alt="Screenshot 2023-11-07 201323" src="https://github.com/a13xh7/QaraTMS/assets/145110/9b96dd8c-9474-45cb-87eb-078d0421eaf3">

**Comment by a13xh7** [comment]
@libregeek The problem is that the js scripts are not loaded. I tested with built-in laravel development server (`php artisan serve`) and test suite cteation works. 

I think the problem is in Apache settings.

**Comment by libregeek** [comment]
Hello @a13xh7 Thanks for your quick and prompt response. I installed QaraTMS on a dedicated subdomain and it works fine now. I am now able to create Test Suites and Test Cases and execute them. However, the test suites are not listed when I first click on the Repository link. The following error is shown on the developer console on Mozilla Firefox (I haven't tested it on other browsers):
<img width="503" alt="Screenshot 2023-11-08 131127" src="https://github.com/a13xh7/QaraTMS/assets/145110/68c1a5aa-1187-4a79-b41b-d35376f112ef">

The Test Suites and Test Cases appear if I do a CTRL+Shift+R (hard refresh) on the browser screen. Do you know why this happens?

**Comment by a13xh7** [comment]
Maybe because of browser cache. Do you have same error in chrome browser?

**Comment by libregeek** [comment]
No. there is no error with Google Chrome.
