### ISSUE TITLE
Error during Authorization on Chrome

### ISSUE THREAD

**Issue by pyuscherbakov** [a13xh7/QaraTMS#24]
**Subject: Bug Report: Error during Authorization in QaraTMS on Chrome**

**Description:**
1. **Steps to Reproduce:**
   - Go to the QaraTMS main page as an unauthorized user.
   - Enter the username and password in the respective fields.
   - Click the "Login" button.

2. **Expected Result:**
   - After entering the correct credentials, the user should successfully log in to the system.

3. **Actual Result:**
   - After entering the username and password and clicking the "Login" button, Chrome displays an error: "The information you’re about to submit is not secure."

4. **Environment:**
   - Browser: Chrome Version 119.0.6045.159 (Official Build) (64-bit)

**Attachments:**
- Screen recording: [link to the screen recording](https://jam.dev/c/2f47dbeb-c298-44b4-b675-87fc95147ff3)

**Comment by a13xh7** [comment]
Hello @pyuscherbakov 

I tested with local server - `php artisan serve` and authorization works as expected.
Could the problem be in the web server (apache/nginx) settings?

**Comment by pyuscherbakov** [comment]
Could this be due to the fact that HTTP is used?

**Comment by pyuscherbakov** [comment]
Switched to HTTPS and the error disappeared
False alarm, sorry for bothering you
