### ISSUE TITLE
Clicking the down arrow on a test step, when it's the last step

### ISSUE THREAD

**Issue by roguefalcon** [a13xh7/QaraTMS#26]
Really enjoying your software so far.  Good job.

One small issue... If you create a test step and then click the sorting down arrow, it will delete the step.  I would expect it to either not be clickable or I would expect it to do nothing.

![qaraTMS - issue with down arrow](https://github.com/a13xh7/QaraTMS/assets/1078351/afc03678-6ff7-4028-815a-224a8db8434d)

If you click the up arrow twice you get the same behavior but it's a little different.  When you click it the first time it moves the step above the "Steps" heading.  Clicking it again will delete it.

![qaraTMS - issue with up arrow](https://github.com/a13xh7/QaraTMS/assets/1078351/b4087a41-906c-42fd-9241-2e335611f85a)

Again, these are very small issues but I figured since the software is pretty amazing, I'd try to help out a little by pointing them out.

**Comment by roguefalcon** [comment]
I should have mentioned that I'm using the `docker compose` method and I pulled the code repository this morning.

**Comment by a13xh7** [comment]
fixed

**Comment by roguefalcon** [comment]
Amazing!  Thanks so much.
