### ISSUE TITLE
Bug: Permission related columns not limited to 125 characters

### ISSUE THREAD

**Issue by ENG3PLabs** [a13xh7/QaraTMS#48]
Since MySQL 8 is supported, the length of some of the fields in the permissions related table [should be limited to 125 characters](https://spatie.be/docs/laravel-permission/v5/prerequisites#content-schema-limitation-in-mysql).

Since the values currently come from use, I don't think that this is a big issue though.

Could be fixed in #49.

**Comment by a13xh7** [comment]
updated to laravel 11
