### ISSUE TITLE
renderTestCaseEditForm() not working properly

### ISSUE THREAD

**Issue by candragirinata** [a13xh7/QaraTMS#52]
![image](https://github.com/user-attachments/assets/f6e8c106-b055-40d1-9e3c-b8a40ab184eb)
![image](https://github.com/user-attachments/assets/45856ac7-df0a-4b79-bca5-9f9b12a41ba4)

hello , i want to ask function renderTestCaseEditForm() not working properly, may be some help?

**Comment by a13xh7** [comment]
this functionality is not ready yet
