### ISSUE TITLE
Database Migration fails for Create Permission when we run with the latest code. 

### ISSUE THREAD

**Issue by bhattisatish** [a13xh7/QaraTMS#53]
If we checkout the latest code and try to create a new setup, it fails with the following error:
![image](https://github.com/user-attachments/assets/982317e9-bec8-4b05-aff3-1283d1c83f4e)
"Access to undeclared static property $Spatie\Permission\PermissionRegistrar::$pivotPermission"

This is because of the following [line](https://github.com/a13xh7/QaraTMS/blob/2bc0191f05395edfb7e1f96acfb7ae15222ae6a5/database/migrations/2022_06_09_185929_create_permission_tables.php#L54)  in the `database/migrations/2022_06_09_185929_create_permission_tables.php` file.

The issue is due to the updated PermissionProvider library but the migration is using the old api's.
One suggested solution is to regenerate the migration: See https://github.com/spatie/laravel-permission/discussions/2576#discussioncomment-8417545
I haven't tried it.

For now the easiest workaround I found was the following:

1. Checkout `dc9c8fef599c22e5abd5c5402510f953a17dae7a`
2. Run `composer install`
3. Run `php artisan key:generate`
4. Update the .env file
5. Run `php artisan migrate`
6. Run `php artisan db:seed --class=AdminSeeder`
7. Pull the latest
8. Rerun `composer install`

**Comment by moussaouinassim** [comment]
Hi team,
Is their any update on this issue?

**Comment by a13xh7** [comment]
fixed
