### ISSUE TITLE
Ошибка при переключении в режим редактирования на странице /test-case/1

### ISSUE THREAD

**Issue by tihant** [a13xh7/QaraTMS#7]
На странице /test-case/1, при клике на эту кнопку

```
  <button type="button" class="btn btn-outline-dark btn-sm mb-2"
          onclick="renderTestCaseEditForm(1)">
      <i class="bi bi-pencil px-1"></i>
  </button>
```
Ничего не происходит и ошибка в консоле браузера:

1:143 Uncaught ReferenceError: renderTestCaseEditForm is not defined
    at HTMLButtonElement.onclick (1:143:57)

**Comment by a13xh7** [comment]
@tihant проблема в том, что не грузятся нужные js файлы. Проверьте вкладку network в консоли браузера. 
Неправильно настроен хостинг / веб сервер.
