### ISSUE TITLE
 Error saving message

### ISSUE THREAD

**Issue by PolinaDominion** [a13xh7/QaraTMS#9]
When I save and edit the steps containing the code, they transform
What I want to keep:( http://sabir.greenred.ru/chrome_oE6VAo9htz.png)
Save - Update
What is really saved: http://sabir.greenred.ru/chrome_63o89dCGk6.png

**Comment by a13xh7** [comment]
@PolinaDominion can you send me that code? 

I was able to save html or simple xml code - https://prnt.sc/xqJI9POQhSDi

**Comment by PolinaDominion** [comment]
Sure
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE yml_catalog SYSTEM "shops.dtd">
<yml_catalog date="2021-07-16 08:32">
<shop>
<name>Name</name>
<company>Appa</company>
<url>https://tlt.kuva.ru</url>
<local_delivery_cost>300</local_delivery_cost>
<currencies>
<currency id="RUR" rate="1"/>
</currencies>
<pickup-options>
<option cost="0" days="0" order-before="18"/>
</pickup-options>

<delivery>false</delivery> new!!! 

<delivery-options>
<option cost="0" days="1" order-before="18"/>
</delivery-options>

**Comment by PolinaDominion** [comment]
> <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE yml_catalog SYSTEM "shops.dtd">
<yml_catalog date="2021-07-16 08:32">
<shop>
<name>Ка</name>
<company>Э</company>
<url>https://ta.ru</url>
<local_delivery_cost>300</local_delivery_cost>
<currencies>
<currency id="RUR" rate="1"/>
</currencies>
<pickup-options>
    <option cost="0" days="0" order-before="18"/>
</pickup-options>
<delivery-options>
    <option cost="0" days="1" order-before="18"/>
</delivery-options>...

**Comment by a13xh7** [comment]
@PolinaDominion I saved it as simple text in step description. Maybe you copied it and inserted with some css styles, that's why the editor couldn't handle it.

**Comment by a13xh7** [comment]
https://prnt.sc/RsKGbV48X0uF
